"""The config module is the replaceable deploy seam (spec §13). These tests pin
the seam's contract: env vars in, resolved values out, sane defaults.

Reimport `config` fresh per case so env changes take effect (module reads env at
import time, like it does in the runtime)."""

import importlib

import pytest

pytestmark = pytest.mark.unit


def _fresh_config(monkeypatch, env):
    for k, v in env.items():
        monkeypatch.setenv(k, v)
    import config

    return importlib.reload(config)


def test_default_model_is_L0_opus(monkeypatch):
    monkeypatch.delenv("AGENT_MODEL_ID", raising=False)
    cfg = _fresh_config(monkeypatch, {})
    assert cfg.DEFAULT_MODEL_ID == "global.anthropic.claude-opus-4-8"


def test_model_id_overridable_by_env(monkeypatch):
    cfg = _fresh_config(monkeypatch, {"AGENT_MODEL_ID": "global.anthropic.claude-sonnet-4-6"})
    assert cfg.DEFAULT_MODEL_ID == "global.anthropic.claude-sonnet-4-6"


def test_gateway_url_reads_autogenerated_name(monkeypatch):
    monkeypatch.delenv("AGENTCORE_GATEWAY_URL", raising=False)
    cfg = _fresh_config(
        monkeypatch,
        {"AGENTCORE_GATEWAY_RECEIPTSGATEWAY_URL": "https://gw.example/mcp"},
    )
    assert cfg.GATEWAY_URL == "https://gw.example/mcp"


def test_explicit_gateway_url_wins(monkeypatch):
    cfg = _fresh_config(
        monkeypatch,
        {
            "AGENTCORE_GATEWAY_URL": "https://explicit/mcp",
            "AGENTCORE_GATEWAY_RECEIPTSGATEWAY_URL": "https://auto/mcp",
        },
    )
    assert cfg.GATEWAY_URL == "https://explicit/mcp"


def test_memory_id_unset_by_default(monkeypatch):
    for k in ("MEMORY_RECEIPTSAGENTMEMORY_ID", "AGENTCORE_MEMORY_ID"):
        monkeypatch.delenv(k, raising=False)
    cfg = _fresh_config(monkeypatch, {})
    assert cfg.MEMORY_ID == ""  # empty => memory degrades gracefully (spec §5.2)
